version: '3'

services:

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=caching_sha2_password
        restart: always
        ports:
            - 3306:3306
        volumes: 
            - ./init-files/db:/docker-entrypoint-initdb.d
            - ./init-files/cnf:/etc/mysql/conf.d
        environment: 
            - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}