version: '3.8'

services:

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        volumes: 
            - ./init-files/db:/docker-entrypoint-initdb.d
            - ./init-files/cnf:/etc/mysql/conf.d

        environment: 
            MYSQL_ROOT_PASSWORD: password
        